Model:
    input_len: 128
    hidden_len: 128
    catg_num: 2
    aggregation: "DetectBERT" # "addition", "average", "random", "DetectBERT"

Train:
    device: 4 # what GPU ID!
    n_epochs: 20 # same as in paper
    save_steps: 50000
    total_steps: 2500000

Optimizer:
    opt: lookahead_radam
    lr: 0.0002 # in code 0.0002, in paper 0.0001
    opt_eps: null  # not mentioned in paper
    opt_betas: null # not mentioned in paper
    momentum: null  # not mentioned in paper
    weight_decay: 0.00001 # not mentioned in paper

Master:
    subset: "250125"